/**
 * `ideaspaces skills [<name>]` — list the skill catalog, or print one skill's
 * markdown. The catalog is protocol-owned; this command is its CLI presentation.
 *
 * `ideaspaces skills sync [--check]` — generate committed `.claude/skills/`
 * pointers from this space's `_agent/skills/`, level by level (see
 * ../skills-sync.ts for the placement model).
 */

import { listSkills, readSkill } from "@ideaspaces/protocol";
import { createOutput } from "../output.js";
import { syncSkillPointers } from "../skills-sync.js";
import type { CommandDef } from "../types.js";

export const skillsCommand: CommandDef = {
  name: "skills",
  description: "List the skill catalog, print one skill, or sync space skills to .claude/skills",
  usage: "ideaspaces skills [<name>] | ideaspaces skills sync [--check]",
  examples: [
    "ideaspaces skills",
    "ideaspaces skills capture",
    "ideaspaces skills sync          # generate/refresh .claude/skills pointers",
    "ideaspaces skills sync --check  # report drift without writing; exit 3 when stale",
  ],
  async run(args, flags, global) {
    const output = createOutput(global);
    const name = args[0];
    if (name === "sync") {
      if (args.length > 1) {
        output.error(`Unexpected argument \`${args[1]}\` — usage: ideaspaces skills sync [--check]`);
        return 1;
      }
      const check = Boolean(flags.check);
      const report = await syncSkillPointers(process.cwd(), { check });
      if (!report) {
        output.error(
          "Not inside an ideaspace — no `_agent/foundation.md` found walking up from here.",
        );
        return 1;
      }
      const drift =
        report.created.length + report.updated.length + report.removed.length > 0;
      const lines: string[] = [];
      const verb = check ? "would " : "";
      for (const p of report.created) lines.push(`  ${verb}create ${p}`);
      for (const p of report.updated) lines.push(`  ${verb}update ${p}`);
      for (const p of report.removed) lines.push(`  ${verb}remove ${p}`);
      for (const p of report.skipped)
        lines.push(`  skip ${p} — not generated by sync; left untouched`);
      lines.push(
        drift || report.unchanged
          ? `${check ? "Drift check" : "Synced"}: ${report.created.length} created, ${report.updated.length} updated, ${report.removed.length} removed, ${report.unchanged} unchanged.`
          : "No `_agent/skills/` entries to sync.",
      );
      if (report.privateAgentLevels.length) {
        lines.push(
          `Note: \`_agent/\` is gitignored at ${report.privateAgentLevels.join(", ")} — committed pointers would dangle for cloners; consider gitignoring \`.claude/skills/\` there too.`,
        );
      }
      output.result(report, lines.join("\n"));
      return check && drift ? 3 : 0;
    }
    try {
      if (name) {
        const skill = await readSkill(name);
        output.result(
          { name: skill.name, description: skill.description, content: skill.content },
          skill.content,
        );
      } else {
        const skills = await listSkills();
        output.result(
          skills,
          skills.map((s) => `${s.name}${s.description ? `  —  ${s.description}` : ""}`).join("\n"),
        );
      }
      return 0;
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      // Named lookups that fail point back at the list.
      output.error(name ? `${msg}\nRun \`ideaspaces skills\` to list available skills.` : msg);
      return 1;
    }
  },
};
